name: multi-line-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Multi-line-shell-commands
        run: | 
            echo "First Output" 
            echo "Second Output"
  
